name: structured_ad_lg
version: 0.1.5
description: |-
  The package is to handle administrative division on local government(ad_lg) as structured data, and make for conveniently operation in development of e-administration system.
repository: https://github.com/HALKA9000-NIIP/jpn_local_gov
environment:
  sdk: '>=2.9.0 <3.0.0'
dependencies:
  yaml: ^2.2.1
